
export default {
    BOY_SCORE: 'BOY_SCORE',
    GIRL_SCORE: 'GIRL_SCORE',
    TIE: 'TIE',
    BOY_WIN: 'BOY_WIN',
    GIRL_WIN: 'GIRL_WIN',
  
  
    BOY_PAPER: 'BOY_PAPER',
    BOY_STONE: 'BOY_STONE',
    BOY_SCISSORS: 'BOY_SCISSORS',
    BOY_LOSS: 'BOY_PAPER',


    GIRL_PAPER: 'GIRL_PAPER',
    GIRL_STONE: 'GIRL_STONE',
    GIRL_SCISSORS: 'GIRL_SCISSORS',
    GIRL_LOSS: 'GIRL_LOSS',

    THREW_RESULT: 'THREW_RESULT'



};